### ISSUE TITLE
Missing 'dist/module/src' folder for the module import

### ISSUE THREAD

**Issue by pyoner** [upstash/upstash-redis#10]
```Failed to resolve entry for package "@upstash/redis". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@upstash/redis". The package may have incorrect main/module/exports specified in its package.json.```

**Comment by ademilter** [comment]
Thank you for the feedback. please use version [v0.1.22](https://github.com/upstash/upstash-redis/releases/tag/v0.1.22)

**Comment by pyoner** [comment]
Thank you for the fast fix!
