### ISSUE TITLE
@upstash/redis import in file causing module to be imported dynamically

### ISSUE THREAD

**Issue by cathykc** [upstash/upstash-redis#109]
This is an issue as of `1.3.2-alpha.0` - fine for 1.3.0 (the version we've now pinned our application to).

Platform: Next.js 12.0.7

We have a very simple file (`redis.ts`):
```
import { Redis } from "@upstash/redis";
const redis = Redis.fromEnv();
export default redis;
```

We then import this in another file (`import redis from "./redis";`) - The `redis` object is now a promise that needs to be awaited before we can access the exported properties. This is leading us to believe that Next is interpreting something upstream as needing to be dynamically imported.

**Comment by chronark** [comment]
Hey @cathykc,
thank you for reporting this.

We recently found something similar in nextjs I believe. For some reason it didn't load environment variables properly, when creating such a utility `redis.ts` file.
The fix was to just not do that and create a new `Redis.fromEnv()` instance instead of importing from the utility file, which doesn't cause any issues, as the sdk is completely stateless.

However it's not a perfect solution either. I will dig some more.

In the meantime, can you try upgrading to `v1.6.0` and see if this behavior still exists?

**Comment by cathykc** [comment]
We discovered the error while using v1.6.1 so the problem definitely still exists! Keep us posted - we'll pin it at 1.3.0 for now.

**Comment by chronark** [comment]
I will take a look at this on monday or tuesday.
It should be fairly easy to reproduce, thanks to your code snippet and explanation above.

**Comment by chronark** [comment]
Hey @cathykc,

I created [an example](https://github.com/upstash/upstash-redis/tree/main/examples/nextjs_export) but it works as expected.

I also tried using default exports, that sitll works.

Can you compare it with your code and let me know what's different?

**Comment by Ali-Hussein-dev** [comment]
@chronark yes it is the same the issue I had but also it worked fine in a minimal repo!!

**Comment by Ali-Hussein-dev** [comment]
[repo](https://github.com/Ali-Hussein-dev/bug-reproduce)
here is an example of the bug

**Comment by chronark** [comment]
Hmmm, it might be caused by `getServerSideProps`.
I'll play around with it,
thanks for sharing.

**Comment by chronark** [comment]
Hey @Ali-Hussein-dev @cathykc 
I tried this again and it worked just fine.

```
git clone https://github.com/Ali-Hussein-dev/bug-reproduce.git
cd bug-reproduce
yarn add @upstash/redis@latest

UPSTASH_REDIS_REST_URL=... UPSTASH_REDIS_REST_TOKEN=.. yarn dev
```

Also tried it deployed on vercel and that works too

**Comment by Ali-Hussein-dev** [comment]
@chronark so we should update `@upstash/redis` to the last version `1.9`

**Comment by chronark** [comment]
@Ali-Hussein-dev have you had time to try this yet?

**Comment by Ali-Hussein-dev** [comment]
@chronark mmm, I tried it but unfortunately, it didn't work. I used Nx workspaces if that matters.

**Comment by chronark** [comment]
Oh I remember I had plenty of issues with that as well.
Do you have a minimal example you could share?
otherwise I'll try creating one next week

**Comment by Ali-Hussein-dev** [comment]
@chronark [Repo with Nx](https://github.com/Ali-Hussein-dev/kb-playground), 
however, I recommend creating a new one with the last version of Nx.

**Comment by chronark** [comment]
thank you so much.
I'll check it out

**Comment by chronark** [comment]
@Ali-Hussein-dev I'm confused, there's no mention of upstash or redis in that repo?
Did you send the wrong one?

**Comment by Ali-Hussein-dev** [comment]
@chronakr sorry you need to install it. `npm i @upstash/redis` and you are ready to go.
