### ISSUE TITLE
ZAdd with incr option return string instead of number

### ISSUE THREAD

**Issue by rebaz94** [upstash/upstash-redis#116]
Hi,
I'm trying to port this library to a ```Dart``` package and when implementing ```ZAddCommand``` and writing the same test I found that the test is not written for ```incr```, it just copied from previous test.

here the test in ```zadd.test.ts``` file
```ts
Deno.test("incr", async (t) => {
  await t.step("returns the number of changed elements", async () => {
    const key = newKey();
    const member = randomID();
    const score = Math.floor(Math.random() * 10);
    await new ZAddCommand([key, { score, member }]).exec(client);
    const newScore = score + 1;
    const res = await new ZAddCommand([
      key,
      { ch: true }, // it should be { incr: true }
      { score: newScore, member },
    ]).exec(client);
    assertEquals(res, 1);
  });
});
```

Then when I change to ```incr``` the result will return as a ```String``` instead of ```number```, and that cause to throw exception as ```ZAddCommand``` result should be number or null according to the [result bound](https://github.com/upstash/upstash-redis/blob/f45ddfd070505ea41af21e9309c1529f1e164e69/pkg/commands/zadd.ts#L18).

here the dart code
```dart
group('incr', (){
    test('returns the number with added increment', () async {
      final key = newKey();
      final member = randomID();
      final score = 10;
      await ZAddCommand.single(key, score: score, member: member).exec(client);
      final newScore = score + 1;
      final res = await ZAddCommand.single(
        key,
        score: newScore,
        member: member,
        opts: zAddBy(incr: true),
      ).exec(client);
      expect(res, score + newScore);
    });
  });
```

So does it is a bug or should ```ZAddCommand``` handle both number and string as a result?

Thank you

**Comment by chronark** [comment]
Hey @rebaz94 

Good catch!, I've [fixed the test](https://github.com/upstash/upstash-redis/pull/117/files) but it returns correctly as `number`. Javascript is pretty loose when it comes to types, so maybe that's why it works in javascript but not in dart?

According to the [redis specs](https://redis.io/commands/zincrby/) it returns a number as string, so you need to manually convert that to number in your client.

Btw, awesome to see a client in dart, I'd love to check it out!

**Comment by rebaz94** [comment]
Thank you for the quick response.

Yes I handled manually to convert to number.

I just started the implementation, will open source it soon if I have time to complete it. If you interested to give some advice let me know I will add to the git before I implement all commands.

**Comment by chronark** [comment]
yes I'd appreciate if you add me, so I can check it out.
I have never used dart before, but maybe I can help.

and thank you for open sourcing it, I'm sure others will appreciate it as well.

I'll close this for now, please open another issue if you find something else.
