### ISSUE TITLE
 TypeError: Only HTTP(S) protocols are supported

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [upstash/upstash-redis#12]
## current behavior  
` TypeError: Only HTTP(S) protocols are supported`
I am getting an error when trying to cache or getting cache while running my next app locally. 

@upstash/redis : ^0.1.3
Nextjs: 12.0.0

**Comment by enesakar** [comment]
How do you configure your next app?

**Comment by mohamedGamalAbuGalala** [comment]
@ademilter @enesakar 
What happens if we want to connect to a local Redis using a URL like this: ' redis://localhost:6379`?

**Comment by rklubenspies** [comment]
I'm in a similar position as @mohamedGamalAbuGalala use case -- my reason for connecting to a `localhost` endpoint is for local testing and development. If I want to run a local Redis image with Docker just for high use development tasks, is there a way to do that while still using the Upstash Redis client in my code?

**Comment by chronark** [comment]
@rklubenspies there is no way to run our redis server locally, however there are some community projects to run a rest api compatible proxy:
by @mna: https://github.com/mna/upstashdis
by @hiett: https://github.com/hiett/serverless-redis-http
