### ISSUE TITLE
Unicode converting from UTF-16 to UTF-32 then failing on JSON.parse

### ISSUE THREAD

**Issue by cathykc** [upstash/upstash-redis#120]
We're storing an object via `hset` that contains the following unicode character (an emoji) `\ud83e\udef6`. When we retrieve the value via `hgetall` we get `\U0001faf6` back which is the `UTF-32` encoding of the original character. This causes the deserializer to fail.

Is there a reason that these characters are getting converted from different encoding types? And what would be the recommended work around here?

Error we receive back from `hgetall`:

```
FetchError: invalid json response body at [URL] reason: Unexpected token U in JSON at position 330
```

We then fetch the response using `/hgetall/` REST API to inspect it - (`res.text()`) and it's telling us the unicode character was transformed to UTF-32

**Comment by cathykc** [comment]
Perhaps the solution here is to be able to define a custom serializer? I notice we can do that for deserializers.

**Comment by chronark** [comment]
Hmm, we're not doing anything other than calling `JSON.parse` when deserializing. I'm not sure what's causing this but I'll try it myself.

Yeah, can you try it without deserialization:
```ts
new Redis({
  // ...
  automaticDeserialization: false
})
```
that will give you the string response straight from redis.

If that also converts the string in to UTF-32, then we'll need to fix it in our redis server.

**Comment by chronark** [comment]
Thanks, 
I will try to debug this asap, but I can't promise you anything until the end of next week.

**Comment by chronark** [comment]
I've been testing this and it's also happening with `ioredis`

**Comment by chronark** [comment]
I'll close this due to inactivity, please reopen if you have more questions

**Comment by cathykc** [comment]
Hey! Sorry for not replying - we ended up solving this by with `encodeURI`.

Setting - `encodeURI(JSON.stringify(VALUE_TO_STORE_IN_REDIS))`
Getting -`JSON.parse(decodeURI(VALUE_RETREIVED_FROM_REDIS)` - this returns the original unicode characters

Thanks for looking into this!

**Comment by cvle** [comment]
Running into the same issue!

Very easy to reproduce, just run:

```
➜ SET bugtest 🫠
OK
➜ GET bugtest
Bad escaped character in JSON at position 12
```

**Comment by pavvell** [comment]
running into the same issue as @cvle, on the backend I replaced `upstash/redis` with `ioredis` because setting `automaticDeserialization = false` did not help. but now on the frontend the issue is the same, but on the frontend I can't use anything other than upstash restapi... 

@chronark  do you think there will be an option in the future for the rest api to return un-desirialized (raw) data from redis?
