### ISSUE TITLE
LPOP / RPOP should support second argument

### ISSUE THREAD

**Issue by magicspon** [upstash/upstash-redis#124]
example:
```javascript
const ids = await upstashClient.rpop(`myList`, 4)
```

error: Expected 1 arguments, but got 2.ts(2554)

https://redis.io/commands/lpop/ (counter arg added in version 6.2)

Cheers

**Comment by chronark** [comment]
I've been adding v6.2 support slowly, whenever someone needed it because other things always took priority.

I'll implement this tomorrow morning.

Thanks for reporting.

**Comment by chronark** [comment]
`v1.8.0` includes the count option now.

```ts
const res = await redis.lpop<string[]>("key", 2)
```

Please open a new issue if you need anything.

**Comment by magicspon** [comment]
Legend... thanks for adding this so quickly
