### ISSUE TITLE
get() returns base64 encoded string instead of actual value

### ISSUE THREAD

**Issue by obibring** [upstash/upstash-redis#1246]
I'm using `set(key, json_string)` to store data and seeing the correct string in the Dashboard. Fetching that data w/ `get(key)` returns a base64 encoded string, not the original string passed to the `set()` method.

**Comment by ogzhanolguncu** [comment]
By default our SDK decodes base64 so it should work out of box. Can you share your code?

**Comment by ytkimirti** [comment]
Closing as stale, please reopen if you can reproduce the issue
