### ISSUE TITLE
Timeouts on Netlify

### ISSUE THREAD

**Issue by madsem** [upstash/upstash-redis#133]
Hi,

we've updated to the latest version and since then our functions on Netlify time out.
Exactly on the line where we connect to redis, no exceptions or anything just a timeout after 10 seconds.

Locally via `netlify dev` everything works.

Any idea what changed that could cause this?

```js
const { Redis } = require("@upstash/redis");

const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
});


module.exports.handler = async (event, context) => {
  // only allow GET requests
  if (event.httpMethod !== "GET") {
    return {
      statusCode: 405,
      body: JSON.stringify("Method not allowed."),
    };
  }

  try {

    const siteId = event.path.replace("/some-path/", "").split("/")[0];

   console.log('blah'); // works...
   const data = await redis.get(siteId); // timeout after 10 seconds
   console.log('nope'); // never logs...
...
...
```

**Comment by chronark** [comment]
Hey, what was the last version that worked?

**Comment by madsem** [comment]
Before we were running on `1.0.x`, this is in our old package.json:
`"@upstash/redis": "^1.0.3",`

**Comment by madsem** [comment]
I've tested several things now:

adding `console.log(await redis.ping());` yields no output, still just a timeout.

I downgraded to version 1.0.3, and it started working again, without any code changes...

**Comment by madsem** [comment]
@chronark yes exactly, it's a regular lamba function. :)

**Comment by chronark** [comment]
@madsem 
ok, this is because nodejs doesn't have `fetch` natively before v18.
unfortunately the error message is just not useful at all.
The solution is to just replace this:

```ts
- const { Redis } = require("@upstash/redis")
+ const { Redis } = require("@upstash/redis/with-fetch")
```


As an alternative you could load a polyfill yourself.

**Comment by madsem** [comment]
Ahhhh okay, makes sense. I added a `.nvmrc` file to my repo and thought that Netlify will then also use that for Lambda...
Thank you @chronark :)

**Comment by madsem** [comment]
PS: will this `const { Redis } = require("@upstash/redis/with-fetch")` fail whenever Lambda is silenty updated to use Node18 without us realizing?

**Comment by chronark** [comment]
The only difference between the two is 

```ts
import "isomorphic-fetch"
```

Importing it while you are using node18 works without issues, as it only polyfills if `fetch` is not available.
So I doubt it will cause troubles, but of course i can not vouch for another dependency.

**Comment by madsem** [comment]
You're a rockstar @chronark  :)

Thanks very much, appreciate you.
