### ISSUE TITLE
TypeError: Only HTTP(S) protocols are supported

### ISSUE THREAD

**Issue by jesper-bylund** [upstash/upstash-redis#139]
Using Nextjs on vercel, using the guide as described here: 
https://docs.upstash.com/redis/quickstarts/vercel

(btw, these key names 'UPSTASH_REDIS_REST_URL', 'UPSTASH_REDIS_REST_TOKEN', no longer correlate with what you get in the details tab so it's a source of confusion.)

results in the error:
`TypeError: Only HTTP(S) protocols are supported`
Both locally and on vercel.

My Nextjs was generated using the create-next-app.

**Comment by chronark** [comment]
Hey!

I don't understand what you mean the key names don't correlate with the details tab, can you elaborate?
I can see them in our console
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/18246773/183297240-a4fe5435-b3a0-4c20-a71e-ebb66c41ea75.png">

The error message is a pretty good indication, that whatever you are passing to `Redis` is not properly prefixed with `https://`. Can you double check your url is correct?

**Comment by jesper-bylund** [comment]
Hey @chronark you are right on the money.
I couldn't see the rest API example, since it is below the "connect to your database" box. It didn't make sense to me that one of the connection methods would be at some other place.

However I did see this, and instead now getting this error on vercel:
```
WARN	Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

**Comment by jesper-bylund** [comment]
Actually never mind my precious message. It looks like that error was from a previous deploy. Currently debugging a 500 on the endpoint. Will fix, and come back or close.

**Comment by chronark** [comment]
👍  I'll update the docs to make it clearer and we'll think about merging the connection options at some point.

**Comment by jesper-bylund** [comment]
So it turns out my original `TypeError`, my 500 error `error - UpstashError: Unauthorized`, and my latest `TypeError: Cannot read properties of undefined (reading 'startsWith')` are all due to authentication errors.

This happens when the URL or REST token is incorrect, or read incorrect from my dot env file.

I figured this is worth knowing, as it's a bit strange. But I will close this issue as the original problem is resolved.
Thank you!

**Comment by chronark** [comment]
`Cannot read properties of undefined (reading 'startsWith')` is a result of passing `undefined` instead of a `string`
If you are using typescript, it should warn you about this.

We provide `const redis = Redis.fromEnv()` as static constructor, that reads from env and provides a helpful error message if `UPSTASH_REDIS_REST_URL` or `UPSTASH_REDIS_REST_TOKEN` is not found in the environment.

However that's as far as we can go I think. storing and loading the url and token is up to the user and they need to ensure it works.

**Comment by jesper-bylund** [comment]
@chronark The cause was dotenv serving an old version. But I figured it might be worth documenting that there was some confusion on my part. 

I very much appreciate the quick help!

**Comment by DiegoFleitas** [comment]
> Hey @chronark you are right on the money. I couldn't see the rest API example, since it is below the "connect to your database" box. It didn't make sense to me that one of the connection methods would be at some other place.
> 
> However I did see this, and instead now getting this error on vercel:
> 
> ```
> WARN	Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
>   errno: -111,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 6379
> }
> ```

Idem, is very easy to miss & a simple notice would save so much time.

**Comment by chronark** [comment]
We were just talking about this last week and will move a rest example to the top of the page
