### ISSUE TITLE
hsetnx missing

### ISSUE THREAD

**Issue by magicspon** [upstash/upstash-redis#141]
Heyo

`HSETNX` seems to be missing.

https://redis.io/commands/hsetnx/

Cheers

**Comment by chronark** [comment]
Thanks, that must have slipped through
I'm on vacation starting tomorrow, so unfortunately this has to wait until ~22nd-25th of august.

But I'll add it right after

**Comment by magicspon** [comment]
Aces... have a great holiday

**Comment by chronark** [comment]
hmm, looks like it's already implemented, what made you think it's not available?
![image](https://user-images.githubusercontent.com/18246773/185856686-d176b212-fcc8-4218-a60c-0185f385f7f3.png)

@magicspon

**Comment by magicspon** [comment]
Oh yeah... weird, my code editor must have been having a funny 5.
