### ISSUE TITLE
Vercel serverless functions and fetch

### ISSUE THREAD

**Issue by SimonVanherweghe** [upstash/upstash-redis#143]
According to [this paragraph](https://github.com/upstash/upstash-redis#upgrading-to-v140-referenceerror-fetch-is-not-defined) in de readme, it should be possible to get this library running on Vercel. But I can't get this working.

It is stated that Vercel provides a polyfill (can't find this anywhere in the docs), but wen using` import { Redis } from "@upstash/redis"` I get this error:

`,"stack":["ReferenceError: fetch is not defined","    at HttpClient.request (/var/task/node_modules/@upstash/redis/script/pkg/http.js:63:17)","`

When using the `"@upstash/redis/with-fetch";` import, I get this error

```ERROR	Cannot find module '/var/task/node_modules/@upstash/redis/script/platforms/node_with_fetch.js' ERROR	Did you forget to add it to "dependencies" in "package.json"?```

Does this mean none of these two solutions work or did I do something wrong?
I made[ a little test-project for this](https://github.com/SimonVanherweghe/upstash-issue)
I do need to include a regular fetch in my project, that's why it's implemented in this test-project.
I've tried with node-fetch and @vercel/fetch, I get the same errors

**Comment by chronark** [comment]
Oh that's a mistake on my part.
Vercel only polyfills it for Next.js I believe.

I'll check out your example right now.

**Comment by chronark** [comment]
In the meantime, please just add the polyfill manually:

`npm i isomorphic-fetch`

```ts
import { Redis } from "@upstash/redis";
import "isomorphic-fetch"
import type { VercelRequest, VercelResponse } from '@vercel/node';

const redis = Redis.fromEnv();

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const count = await redis.incr("key")
  res.send(JSON.stringify({ count }));
}

```

**Comment by chronark** [comment]
@SimonVanherweghe 
This actually seems to work for me, I've created a PR to show you what I did:
https://github.com/upstash/upstash-redis/pull/144

**Comment by SimonVanherweghe** [comment]
great, isomorphic-fetch does its thing, thanks.

I think the combo with a regular fetch created the issue somehow. 

Thanks for making this clear.
