### ISSUE TITLE
zmscore?

### ISSUE THREAD

**Issue by bbar** [upstash/upstash-redis#146]
Just curious, is support for `redis.zmscore()` on the roadmap for this package?

**Comment by chronark** [comment]
Hey @bbar,
I'm wrapping up a pr to add this among other things, will release this within the hour.

**Comment by bbar** [comment]
Wow, @chronark, the timing on that! Appreciate the work!

**Comment by chronark** [comment]
@bbar 

It's in `v1.13.0`

```ts
const scores = await redis.zmscore("key", [member1, member2, member3])
```


👋

**Comment by bbar** [comment]
@chronark Just wanted to say thanks again for the work.

I'm not sure if a PR for a `console.log()` is a bit over the top (I can submit one if you think I should), but it looks like one of them made it in (line 15):

https://github.com/upstash/upstash-redis/blob/main/pkg/commands/zmscore.ts

**Comment by chronark** [comment]
oh damn, I missed that,
I'll fix it myself, 

thanks for letting me know

**Comment by chronark** [comment]
@bbar see `v1.13.1`
