### ISSUE TITLE
Scan options

### ISSUE THREAD

**Issue by popeating** [upstash/upstash-redis#159]
Trying to use scan command, but i'm not able to set options, for example:
`const result = await redis.scan(0, 'match', 'movie:*');`
return the following error
`UpstashError: ERR unsupported arg type: %!q(<nil>): <nil>`

i'm probably not understanding how to pass the options to the command

**Comment by chronark** [comment]
Hey, the scan signature is like this:
```ts
scan(cursor: number, opts: {
  match?: string
  count?: number
  type?: string
})

```

And take a look at the [tests](https://github.com/upstash/upstash-redis/blob/main/pkg/commands/scan.test.ts), they might help too.

I'm struggling to find a nice solution to autogenerate this type of documentation :/

**Comment by popeating** [comment]
thank you, got it!
