### ISSUE TITLE
Edge URL doesn't work

### ISSUE THREAD

**Issue by Kikobeats** [upstash/upstash-redis#16]
If I do

```jsx
import { auth, set as setUpstash, get as getUpstash } from '@upstash/redis'

auth({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
  edgeUrl: process.env.UPSTASH_REDIS_EDGE_URL
})

getUpstash('upstash')
```

The request failed:

```js
{
  data: null,
  error: 'Request failed',
  metadata: { edge: false, cache: null }
}
```

However, doing the same but removing `edgeUrl` works :(

**Comment by enesakar** [comment]
It worked for me. Can you ensure you are using the latest version and correct edge url? If everything looks good can you share your endpoint (email to support@upstash.com) so we will check if there is anything wrong within database

**Comment by Kikobeats** [comment]
It was an account issue related 👍
