### ISSUE TITLE
Wrong type signature for del command

### ISSUE THREAD

**Issue by kay-is** [upstash/upstash-redis#19]
When I use the `del` command with a `string[]`, I get an error from the service.

    ERR unsupported arg type: ["some-key"]

When I use the `del` command with a `string`, I get an error from the TypeScript compiler.

    Argument of type 'string' is not assignable to parameter of type 'string[]'

**Comment by ademilter** [comment]
which version are you using?

**Comment by kay-is** [comment]
0.1.9

**Comment by ademilter** [comment]
can you check 0.2.1 version

**Comment by kay-is** [comment]
Now, both signatures (`del(a, b, c)` and `del([a,b,c])`) work on the TypeScript side of things, but only the first one is accepted by the Upstash service.

I have to call `client.del.apply(client, [a, b, c])` to make things work with my arrays. Which ESLint marks as a "useless call" because it thinks `del([a, b, c])` is valid too.

**Comment by kay-is** [comment]
Ah, btw. I just noticed I can use the spread operator instead of applying, also I was building the arrays manually in the first place, so I could simply call the `del` function with multiple arguments as it was intended, haha.

I was so deep in, because of the wrong typing in the old version, that I didn't even consider this.

Anyway, now my code is good, but it would be cool if the `del` method would either handle arrays correctly or tell people via TypeScript that you shouldn't use an array in the first place.
