### ISSUE TITLE
NULL RESPONSE after Quota Restriction

### ISSUE THREAD

**Issue by yilmaz-burak** [upstash/upstash-redis#21]
If we use **@upstash/redis** instead of **ioredis** library,
When exceeding the allowed request limit for the day, (ex. 10k requests for regional free db) we get "NULL" response rather than the info of us exceeding the request limit.

**Comment by chronark** [comment]
Do you mean like this:
```ts
const res = await get("key")
res.error // -> undefined
res.data // -> null
```

**Comment by chronark** [comment]
Unfortunately I am unable to reproduce this

```ts
import * as upstash from "@upstash/redis"

async function main() {
  upstash.auth(
    <UPSTASH_REDIS_REST_URL>,
    <UPSTASH_REDIS_REST_TOKEN>
  )

  const { data, error } = await upstash.set("key", "value")
  console.log({ data, error })
  
}
main()
```

correctly logs the following:
```ts
{
  data: null,
  error: 'ERR max daily request limit exceeded. See https://docs.upstash.com/overall/databasetypes for details'
}
```

**Comment by yilmaz-burak** [comment]
Sorry for the late response. It seems that you are right.

When ioredis is used, if error exists, ioredis throws an exception. However, as in the example script you provided, user should check for error explicitly so that they can distinguish between whether the data does not exist or simply the request limit has been exceeded.

**Comment by chronark** [comment]
The next update will move our API more towards what you expect from ioredis and others. `const data = await redis.get("key")` which will throw if there is an actual error like quota exceeded.
