### ISSUE TITLE
TypeError: realFetch.call is not a function

### ISSUE THREAD

**Issue by weixuanteo** [upstash/upstash-redis#212]
Similar to #87 

Included the following import statement but `realFetch.call is not a function` is still thrown.
```js
import { Redis } from "@upstash/redis/with-fetch";
```

**Environment**
AWS Lambda Node.js 16.x

Same error with local dev environment using Node.js 16.15.1

**Comment by chronark** [comment]
Hey @weixuanteo 
I'm working on a fix for this already

please import a fetch polyfill manually for now: For example: `npm i isomorphic-fetch`

```ts
import { Redis } from "@upstash/redis"
import "isomorphic-fetch"

// ...
```

**Comment by weixuanteo** [comment]
> Hey @weixuanteo I'm working on a fix for this already
> 
> please import a fetch polyfill manually for now: For example: `npm i isomorphic-fetch`
> 
> ```ts
> import { Redis } from "@upstash/redis"
> import "isomorphic-fetch"
> 
> // ...
> ```

For some reason, importing a fetch polyfill from `isomorphic-fetch` throws the same error as well.

I manage to resolve it with `cross-fetch` instead and it no longer throws the error.
```js
import { Redis } from "@upstash/redis";
import "cross-fetch/polyfill";
```

**Comment by chronark** [comment]
Hmm, that's very weird, I have that exact same setup running in a lambda right now.

But good to know it works with cross-fetch.

**Comment by weixuanteo** [comment]
I am running version `1.13.1`.

**Comment by chronark** [comment]
Can you share a minimal example where it fails?
