### ISSUE TITLE
Redis documentation improvement:

### ISSUE THREAD

**Issue by jesper-bylund** [upstash/upstash-redis#233]
I'm storing a time series counter in my redis:

<name:time>: 4

And I can redis.get values fine

```redis.get(myname:today)``` returns the count

But I can't mget, for some reason? And I'm not sure why not.
```redis.mget([myname:yesterday, myname:today])``` returns ```[null]```

I can't figure out why not. The test makes me think this should work:
https://github.com/upstash/upstash-redis/blob/main/pkg/commands/mget.test.ts

**Comment by jesper-bylund** [comment]
Discovered the issue. And I would have NEVER figured this out from the test.

This syntax creates an error
```
const queries = ["myname:yesterday","myname:today"];
const data = await redisClient.mget(queries);
// result is data = [null]
```

While this one returns data correctly
```
const queries = ["myname:yesterday","myname:today"];
const data = await redisClient.mget(...queries);
// result is data = [2,5]
```

Not sure if it's mget that should accept both, or if there's a need for an example though.

**Comment by chronark** [comment]
Ooh, I know why. I tried to be clever in the past and apparently it backfired.
I'll fix this in the coming week.
Thank you for finding it

**Comment by ogzhanolguncu** [comment]
@jesper-bylund we now support both array and sprearded values as of this pr https://github.com/upstash/upstash-redis/pull/657
