### ISSUE TITLE
Please add hrandfield

### ISSUE THREAD

**Issue by dikkeduif** [upstash/upstash-redis#248]
Can you please add the following command?

https://redis.io/commands/hrandfield/

**Comment by chronark** [comment]
Yeah I'll add it later today

**Comment by chronark** [comment]
@dikkeduif I have the command working just fine, but typescript is not quite happy yet, because this command can return either a single string, or keys + values
I'll continue working on it tomorrow and can hopefully release it this week

**Comment by dikkeduif** [comment]
@chronark awesome! Take your time
