### ISSUE TITLE
Add hyperloglog commands

### ISSUE THREAD

**Issue by mankins** [upstash/upstash-redis#269]
The [hyperloglog commands](https://redis.com/redis-best-practices/counting/hyperloglog/) like `pfadd` and `pfcount` are useful. Can these be added?

**Comment by chronark** [comment]
Unfortunately we don't support hyperloglog on upstash yet.
See here https://docs.upstash.com/redis/overall/rediscompatibility

 You can vote for it on our roadmap: https://roadmap.upstash.com

**Comment by mdogan** [comment]
Hey @mankins, HLL is in our roadmap, I hope they will be available in next month or so.

**Comment by mankins** [comment]
That sounds great, thanks @mdogan @chronark ... I voted for it. 😀
