### ISSUE TITLE
Error: Unable to find environment variable: `UPSTASH_REDIS_REST_URL` | Nextjs 13

### ISSUE THREAD

**Issue by sagargulati** [upstash/upstash-redis#272]
Greetings,

I'm on Next.js 13 created using `npx create-next-app`

**Packages**
```
    "@upstash/redis": "^1.18.1",
    "axios": "^1.2.1",
    "eslint": "8.29.0",
    "eslint-config-next": "13.0.6",
    "i18next": "^22.1.4",
    "mongodb": "^4.12.1",
    "next": "13.0.6",
    "next-i18next": "^13.0.0",
    "nextjs-progressbar": "^0.0.16",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^12.1.1",
    "react-toastify": "^9.1.1"
```

**index.jsx**
```
import { Fragment, useCallback, useEffect, useState } from 'react';
import { Redis } from '@upstash/redis';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

console.log(process.env.UPSTASH_REDIS_REST_URL); // Works!!!
const redis = Redis.fromEnv(); // Error!!!

export default function Home(props) {
  const { t } = useTranslation('pages');

  const [cache, setCache] = useState('');

  useEffect(() => {
    if (process.env.NODE_ENV === 'development') {
      console.log('Upstash Cache!', JSON.stringify(cache));
    }
    if (cache === null || cache === '') {
      getCache();
    }

    return () => {
      if (process.env.NODE_ENV === 'development') {
        console.log('Upstash Cache effect!');
      }
    }
  }, [cache])
  
  async function getCache() {
    const member = await redis.srandmember("person");
    setCache(member);
  }

  return (
    <Fragment>
            <div className="alpha">Hello!</div>
    </Fragment>
  );
}

export async function getStaticProps({ locale }) {
  if (process.env.NODE_ENV === 'development') {
    console.log('Home page static props');
  }
  return {
    props: {
      ...(await serverSideTranslations(locale, ['global', 'pages'])),
    },
  };
}
```

**.env.development**
```
UPSTASH_REDIS_REST_URL="https://global-awesome-pikachu-12345.upstash.io"
UPSTASH_REDIS_REST_TOKEN="SuperAwesomeToken"
```

**The Error**
<img width="961" alt="image" src="https://user-images.githubusercontent.com/2825887/206718704-067c2240-0e79-4acb-b8d7-0a727051d72e.png">

**Tried & Failed**

```
const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
});
```

**Seems to work with passed as STATIC!**
```
const redis = new Redis({
    url: 'https://global-awesome-pikachu-12345.upstash.io',
    token: '********',
});
```

Even though I have **UPSTASH_REDIS_REST_URL** and **UPSTASH_REDIS_REST_TOKEN** in my `.env.development` file.
I also tried to rename the file to `.env` and I still get the same error.

If I use the code `console.log(process.env.UPSTASH_REDIS_REST_URL)`, **it does fetch the value and shows them** in the console.

Can you suggest what could be wrong?

Thanks!

**Comment by chronark** [comment]
Hmm not sure what's happening here.
Does it work deployed to vercel or wherever you deploy to?

We have an example Herr which worked fine: https://docs.upstash.com/redis/quickstarts/nextjs13


I'd suggest you provide the secrets manually for now to unblock you and I'll try to dig a little in the coming week.

**Comment by sagargulati** [comment]
Even though I have **UPSTASH_REDIS_REST_URL** and **UPSTASH_REDIS_REST_TOKEN** in my `.env.development` file.
I also tried to rename the file to `.env` and I still get the same error.

If I use the code `console.log(process.env.UPSTASH_REDIS_REST_URL)`, it does fetch the value and shows them in the console.

**Comment by chronark** [comment]
Yes as I mentioned above, please use either `getServersideProps`, getStaticProps` or `getInitialProps` to load the data.
you can not use the Redis client in the frontend without exposing the token
