### ISSUE TITLE
 Values ​​containing Japanese cannot be handled

### ISSUE THREAD

**Issue by m-eiichi** [upstash/upstash-redis#299]
I want to lrange the following values ​​with upstash, but only the Japanese part is garbled.

{
  "id": "id",
  "url": "url",
  "text": "japanese-text(here)",
  "user": {
    "name": "name",
    "email": "email"
  }
}

Is there any good solution?

The version of @upstash/redis is 1.19.1

**Comment by chronark** [comment]
Hey @m-eiichi 
garbled in what way?

can you show an example of input and output?

**Comment by m-eiichi** [comment]
It's working as expected.

Thanks for the feedback.
