### ISSUE TITLE
Troubleshooting URL in README is broken

### ISSUE THREAD

**Issue by grempe** [upstash/upstash-redis#300]
In the README of this repo you point to a troubleshooting URL:

https://docs.upstash.com/troubleshooting

This link is broken.

It should probably point to something like:

https://docs.upstash.com/redis/troubleshooting/no_auth

But this points to a sub-page and there should probably be a page that should be created at:

https://docs.upstash.com/redis/troubleshooting

**Comment by chronark** [comment]
@grempe Thanks, I'll take a look

**Comment by chronark** [comment]
Fixed it
