### ISSUE TITLE
ERR unsupported arg type: %!q(<nil>): <nil>

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [upstash/upstash-redis#326]
Hi :wave: 

I am trying to create a json object on redis using the upstash Redis client

```typescript
client.json.set(`user:apiKeys:by-user-id:${user.id}`, "$", { "foo" : "baa" });
```

But, I am receiving this error

```
UpstashError: ERR unsupported arg type: %!q(<nil>): <nil>
```

I've tried to google it but I haven't found anything

Thanks :)

Fra

**Comment by chronark** [comment]
```ts
redis.json.set("user:apiKeys:by-user-id:userId", "$", { "foo" : "baa" });
```
This worked for me, can you double check `user.id` is defined?

**Comment by FrancescoSaverioZuppichini** [comment]
Retested, worked for me (I can see the `json` on upstash redis) but I also got this error

```
error - UpstashError: WRONGTYPE Operation against a key holding the wrong kind of value
```

You were right, the user.id were probably none

**Comment by chronark** [comment]
where did you get that error?
in the databrowser? or in your code?

**Comment by FrancescoSaverioZuppichini** [comment]
In the code, the upload works but I got that error. Creating  a JSON from the cli inside the webapp works

**Comment by chronark** [comment]
So sorry, I didn't see this despite the ping.

It sounds like the key you are using to store your json data, already exists with a different type of value. (eg a `string` or `hash`)

can you try it with a key that is guaranteed not to exist? or `del key` the existing key before?
