### ISSUE TITLE
Cannot use .sort method

### ISSUE THREAD

**Issue by arihant-jain-09** [upstash/upstash-redis#328]
Does redis does not support this command for joining hashes using sorted sets?

**Comment by chronark** [comment]
Can you share an example code snippet that didn't work?

**Comment by arihant-jain-09** [comment]
Lets have three cars with name and age attribute stored in hash.
```
HSET cars#first name Honda age 1970
HSET cars#second name Mercedez age 1980
HSET cars#third name Maruti age 1960
```
We add cars to a sorted set with score being the likes.
```
ZADD cars:likes 999 first
ZADD cars:likes 0 second
ZADD cars:likes 40 third
```
We then need to get the hash values from sorted set we could use a SORT command in general redis.
```
SORT cars:likes BY nosort GET cars#*->name GET cars#*->age
```
OUTPUT:
```
[
  "Mercedez",
  "1980",
  "Maruti",
  "1960",
  "Honda",
  "1970"
]
```

**Comment by arihant-jain-09** [comment]
This does not work
```
const results = await client.sort(
        "cars:likes",
        "BY",
        "nosort",
	"DESC"
        "GET",
        "cars#->name
        "GET",
        "cars#->age",
      );
```

**Comment by chronark** [comment]
Hey, I talked with the redis team and we haven't implemented `sort` yet.
You can always refer to our [compatibility](https://docs.upstash.com/redis/overall/rediscompatibility) page.

That being said, it's still in our roadmap to add, but not in the short term.
