### ISSUE TITLE
Minor confusion on choosing what to import

### ISSUE THREAD

**Issue by gitblit** [upstash/upstash-redis#329]
Hi! Wonderful library & service. It has been **very** easy to get going but I did run into a hiccup I wanted to share. First, I will admit I did not thoroughly read the docs.

I am currently testing out Vercel, Netlify, and Cloudflare Pages hosting to decide where my little SvelteKit app might live. I found it very easy to do this:
```typescript
import { Redis } from '@upstash/redis';
```

and have it build & execute successfully on:
- Vercel
- Netlify

and build but fail at runtime on:
- Cloudflare

Digging into the logs I found references to `process`:
```
process is not defined\n    at new Redis2
```

Obviously this is a Node vs Service Worker api issue. So I consulted your docs, learned about the platform-specific imports, switched to `/cloudflare`, and it worked! 🎉 
```typescript
import { Redis } from '@upstash/redis/cloudflare';
```
That same import also worked on Vercel & Netlify. Presumably because `/cloudflare` is based on fetch and my config approach is to manually specify the `url` & `token` instead of using the platform convenience methods.

I am wondering if there is there a way that `import { Redis } from '@upstash/redis';` could be universal and if you wanted the platform-specific convenience function you imported that? Having said that, I have no idea what else might be happening under-the-hood of the platform-specific import so maybe that is naive of me.

**Comment by chronark** [comment]
Unfortunately it's not easy to combine them in a single export. Mainly because some APIs are just not available in nodejs and vice versa, I tried importing them and only conditionally calling them but that always fails during build time.

The different import paths were an acceptable solution to this problem.
That being said: If there is a way, I'd love to unify to a single import. The workaround is fine but not great.

**Comment by gitblit** [comment]
Thanks for the speedy reply! If you don't think this is actionable, then you won't make me sad if this issue is closed. It seems to be working fine across all 3 platforms 🤞, so I am happy with that.

```typescript
import { Redis } from '@upstash/redis/cloudflare';
import { env } from '$env/dynamic/private';

const redisPrefix = env.UPSTASH_REDIS_PREFIX;
const redisUrl = env.UPSTASH_REDIS_REST_URL ?? '';
const redisToken = env.UPSTASH_REDIS_REST_TOKEN ?? '';

function getRedis(): Redis | undefined {
  if (redisUrl && redisToken) return new Redis({ url: redisUrl, token: redisToken });
}
```

**Comment by chronark** [comment]
I had this tabled for a possible `v2` some day, until then it'll most likely stay like it is currently. But I agree it introduces some friction that I'd like to remove.

Let's leave this open until then, even if only for others to see it and be aware that there are multiple imports :)

Thanks for the issue
