### ISSUE TITLE
Next 13 will set cache: 'force-cache' for all GET requests

### ISSUE THREAD

**Issue by kay-is** [upstash/upstash-redis#330]
When using the new app router of Next 13, GET requests will cache every response by default.

https://beta.nextjs.org/docs/data-fetching/fetching#static-data-fetching

My quick fix for this is to either use the Upstash Redis REST API, or to use a pipeline with the SDK and throw in a `p.set("cacheBuster", Math.random())`, to force the SDK to use a POST request.

I had the same issue with the Kafka SDK.

**Comment by chronark** [comment]
hang on, the sdk always uses post. 
I'm confused now why the pipeline would make a difference

**Comment by kay-is** [comment]
Ah, maybe it also caches with POST, but since the Request looks different with the cachebuster, it misses.

**Comment by chronark** [comment]
It's on my to-do list for next week

**Comment by chronark** [comment]
We fixed this recently, please upgrade to latest
