### ISSUE TITLE
Add support for Geo commands

### ISSUE THREAD

**Issue by patryk-smc** [upstash/upstash-redis#331]
Currently, API client doesn't support Geo commands, while REST API does. It would be nice to have that. Cheers.

**Comment by chronark** [comment]
👍 
I'm adding them as soon as I can, I hope I can get it done until the end of the month.

**Comment by patryk-smc** [comment]
Hey @chronark any updates? Cheers

**Comment by ogzhanolguncu** [comment]
@patryk-smc We finally added GEOADD and rest will be added pretty soon. Sorry for the inconvenience.
