### ISSUE TITLE
Setting the EX param not working correctly?

### ISSUE THREAD

**Issue by lsbyerley** [upstash/upstash-redis#332]
When using the 'EX' param to set an expiration in seconds, the TTL does not show up in the upstash console. Is this value being set incorretly?

```
import { Redis } from '@upstash/redis';

const redis = new Redis({
  url: process.env.UPSTASH_URL,
  token: process.env.UPSTASH_TOKEN,
});

redis.set('ratings-cache', JSON.stringify(ratings), { EX: 3600 });
```

<img width="725" alt="Screenshot 2023-03-17 at 2 19 06 PM" src="https://user-images.githubusercontent.com/3066258/225986649-e35c1229-fbe2-4a0a-947f-fe60a2dcc92b.png">

**Comment by chronark** [comment]
it's lower case I believe, but point taken, I can make both casings work I think

`{ ex: 3600 }`

**Comment by lsbyerley** [comment]
Strange, using `ex` and `EX` do not set a TTL in the upstash console when looking at the Data Browser tab.

**Comment by lsbyerley** [comment]
Ah, okay yeah using lowercase `ex` does show up for me as a TTL in the upstash console. Thanks for clarifying!

**Comment by andrewlu0** [comment]
Is this a known issue? It seems it still doesnt show the TTL seconds in the console for me:
![Screenshot 2023-04-21 at 6 09 42 PM](https://user-images.githubusercontent.com/32521085/233753943-5ce5b7d8-1c74-4433-84cf-da3807dc56f0.png)
![Screenshot 2023-04-21 at 6 09 32 PM](https://user-images.githubusercontent.com/32521085/233753944-fbda9194-c528-4c3b-8afc-5613e676337d.png)

**Comment by jonsherrard** [comment]
@andrewlu0 Did you make this work? I'm having the same issue.

**Comment by chronark** [comment]
I just tried `await redis.set('foo', 'bar', { ex: 1000 })` and it shows up in the databrowser
can you share your code that doesn't work?

**Comment by jonsherrard** [comment]
```ts
// Lots of obsfucated code but roughly:A

  const redis = new Redis({
    url: "https://hidden.upstash.io",
    token: 'hidden'
  });
  const { listingSlug } = req.query;
  const redisKey = listingSlug;
 const uniqueDates = ['array', 'of', 'strings'];
 await redis.set(redisKey, uniqueDates, {
      ex: 60 * 5,
    });
```
