### ISSUE TITLE
Cannot use the sdk in edge runtime

### ISSUE THREAD

**Issue by nexxeln** [upstash/upstash-redis#333]
I'm using the beta Next.js app router. Here's the code for an api endpoint:

```ts
import { LinkSchema, createLink } from "~~/core/link";

export async function POST(request: Request) {
  const body = LinkSchema.safeParse(await request.json());

  if (!body.success) {
    return new Response("Invalid body", { status: 400 });
  }

  const slug = encodeURI(await createLink(body.data));

  return new Response("OK", { status: 200, headers: { slug } });
}
```

Here's the `createLink` function which use the package.
```ts
export async function createLink({ link, type }: Link): Promise<string> {
  let slug = "";

  switch (type) {
    case "emoji":
      const emojiString = getEmojiString(4);

      const didSet = await redis.set(`link/${emojiString}`, link, { nx: true });

      if (!didSet) {
        return createLink({ link, type });
      }

      slug = emojiString;
  }

  return slug;
}
```

This works fine in the nodejs runtime but in the edge runtime it fails, because the package expects buffer which is not compatible with the edge runtime.

**Comment by chronark** [comment]
Try importing from @upstash/redis/cloudflare.

It should work with the regular import too.
Can you share how you are creating the instance?

**Comment by nexxeln** [comment]
Here's how I'm creating the instance
```ts
import { Redis } from "@upstash/redis";

export const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
});
```

Tried importing from @upstash/redis/cloudflare. Still doesn't seem to work.

**Comment by chronark** [comment]
https://github.com/upstash/upstash-redis/blob/main/examples/nextjs_edge/middleware.ts

Can you try this?

**Comment by ogzhanolguncu** [comment]
I tested with `"next": "13.5.5"` and this `middleware.ts
`
```
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { Redis } from "@upstash/redis";

export const redis = new Redis({
  url: process.env.REDIS_URL!,
  token: process.env.REDIS_TOKEN!,
});

export async function middleware(request: NextRequest) {
  const hey = await redis.ping();
  console.log("Hey", { hey });
}
```

It worked fine on both the local and production environments. Maybe the issue you ran into was tied to earlier versions of appRouter, but it seems like they've fixed it now.
