### ISSUE TITLE
ECONNREFUSED - cannot connect to database

### ISSUE THREAD

**Issue by iwo-strzebonski** [upstash/upstash-redis#335]
Hello,
I wanted to use your package to connect to Upstash Redis, however I got this error:

```
file:///Users/iwostrzebonski/git/random-ace-attorney-quotes/node_modules/@upstash/redis/esm/pkg/http.js:101
            throw new UpstashError(body.error);
                  ^
UpstashError: Unauthorized
    at HttpClient.request (file:///Users/iwostrzebonski/git/random-ace-attorney-quotes/node_modules/@upstash/redis/esm/pkg/http.js:101:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PingCommand.exec (file:///Users/iwostrzebonski/git/random-ace-attorney-quotes/node_modules/@upstash/redis/esm/pkg/commands/command.js:55:35)
    at async file:///Users/iwostrzebonski/git/random-ace-attorney-quotes/src/app.ts:34:15
```

I use env copy-pasted from the page (I changed the password to the correct one), and I'm using the `Redis.fromEnv()` function.

Connecting via cURL works.

**Comment by burak-upstash** [comment]
What do you mean by `I changed the password to the correct one`?
If you copy and paste the environment name and value as given in the console, they should work straight out of the box
Could you check that please?

**Comment by chronark** [comment]
Can you double check if you copied the `UPSTASH_REDIS_REST_TOKEN` correctly?
perhaps the trailing `=` is missing

**Comment by chronark** [comment]
can you share your code?
