### ISSUE TITLE
UPSTASH_REDIS_REST_URL is not defined

### ISSUE THREAD

**Issue by vncloudsco** [upstash/upstash-redis#336]
I have configured as instructed but am getting the following error please tell me what to do
 
[ERROR] Uncaught (in promise) ReferenceError: UPSTASH_REDIS_REST_URL is not defined

![image](https://user-images.githubusercontent.com/41409442/228790003-7013b832-3c5c-48ca-8b93-d3f2d65b63c5.png)

**Comment by chronark** [comment]
Closing, please reopen if the problem persists
