### ISSUE TITLE
Server Error TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by bibinthomas123** [upstash/upstash-redis#339]
``` Ts 
import { Redis } from "@upstash/redis";

const DB = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
});

export { DB };
```

i installed the latest version of upstash/redis it still throws an error of  undefined startsWith

**Comment by chronark** [comment]
Please double check your env variables are loaded correctly.
Looks like they're undefined

**Comment by bibinthomas123** [comment]
They are loaded correctly and the env is outside of src

**Comment by chronark** [comment]
I don't understand what that means tbh.

https://github.com/upstash/upstash-redis/blob/main/platforms/nodejs.ts#L100
Here's the relevant code line, which causes the error if the URL is not defined (or token a few lines below)


You can also try `Redis.fromEnv()` which might provide a better error

**Comment by bibinthomas123** [comment]
Tried a lot to fix this nothing worked so created a config.ts exporting the required variables and added config.ts to .gitignore

**Comment by chronark** [comment]
What runtime are you using?

**Comment by bibinthomas123** [comment]
nextjs

**Comment by chronark** [comment]
And how are you setting your env variables?

**Comment by bibinthomas123** [comment]
i created a config.ts file and then setting the variables in the config.ts and then export them , i added the config.ts to .gitignore
