### ISSUE TITLE
[Help] Tokens and custom OAuth to Upstash

### ISSUE THREAD

**Issue by fire17** [upstash/upstash-redis#343]
Hi guys, 
First of all let me say I'm really loving redis and enjoy upstash very much
I've got a question, if this is not the right place please let me know where and I'll post over there..

To give context, I'm seeing how data is becoming the new gold. For example, all my ChatGPT thread history is probably one of the most valuable datasets about me, with all my interests and ideas, but.. I don't have direct (or easy) access to my history data (need to make a scraper for that). Anyways,

I'd like to make and run a system that loads application logic ontop of users' data, while the data itself belongs to the users. When I say belongs I mean, "they" "host" it... This is where upstash comes in.. 😏

Imagine I make a site (like fb or something) and when users login to their account for the first time, they will be asked where they want to host their data. I'd really like the first option to be - _Integration with Upstash_

Much like OAuth, with one click, they should be able to either: log into their existing upstash account OR create a new upstash account (speedy 0 setup).
Then, automatically create a new db and generate a custom token, that will be sent back to our system, and with it, we can pull and edit the user's data based on his interactions in the app
At any given moment the user can choose to disable the token they have given us, and exit the app or platform while still having access to their own private data.

Let me know if this is clear, hope I explained it well enough.
And especially if this is already possible
If not then who or how can we make this work ? 

As I see it it will take 2 things to make it work:
1. Token creation to manage a specific db instance
2. Upstash user integration - which includes
    - login/fast creation of user based on the email given from our system 
    - create a db with uid and send the auth token back

I think it should be fairly easy and straight forward (maybe some of it is already available not sure) would love to hear more from someone with more insight on this..

Thanks a lot and all the best
Have a good one

**Comment by chronark** [comment]
We have a developer api, you can use to create databases on your own account or on behalf of your users.

If you would like to explore building an integration together similar to fly.io + upstash, then please send us an email to support@upstash.com

we're already offering a dashboard via oauth to users coming from fly
