### ISSUE TITLE
Telemetry in cloudflare

### ISSUE THREAD

**Issue by ambravo** [upstash/upstash-redis#348]
The package assumes the existence of the `process` object when determinining if the user wants to opt out of telemetry.
This object does not exist in CLoudflare nodes, hence it throws and error.

✘ [ERROR] Uncaught (in promise) ReferenceError: process is not defined

  enableTelemetry: !process.env.UPSTASH_DISABLE_TELEMETRY,
@upstash/redis/esm/platforms/nodejs.js:42:30

**Comment by chronark** [comment]
I just fixed this in v2.20.6

**Comment by ambravo** [comment]
That was fast! I updated the dependencies and worked.
