### ISSUE TITLE
upstash-redis zadd incompatible with ioredis & throws error when using ioredis zadd arguments

### ISSUE THREAD

**Issue by btakita** [upstash/upstash-redis#351]
Upstash requires a param object with score & member.

```ts
import { Redis } from '@upstash/redis'
const redis = new Redis()
redis.zadd('my-key', { score: 1, member: 'member' })
```

Ioredis requires 2 separate arguments for score & member.

```ts
import Redis from 'ioredis'
const redis = new Redis()
redis.zadd('my-key', 1, 'member')
```

The following will throw an error `Cannot use 'in' operator to search for 'score' in 1`:

```ts
import { Redis } from '@upstash/redis'
const redis = new Redis()
redis.zadd('my-key', 1, 'member')
```

**Comment by chronark** [comment]
Hey,
yeah that's by design

@upstash/redis is not a drop in replacement for ioredis, but aims for a better typescript experience, rather than following `RESP` as closely as possibble

**Comment by btakita** [comment]
@chronark Would you consider maintaining compatibility with the function arguments, to allow codebases to be more interoperable with development environments which may use a local instance of redis & ioredis?

Otherwise, the programmer has to add ad hoc compatibility:

```ts
export function redis__zadd(
	redis_OR_pipeline:Redis|IoRedis|ChainableCommander,
	redis_key:string,
	score:number,
	member:string
) {
	const ioredis__redis_OR_pipeline = redis_OR_pipeline as IoRedis
	if (
		ioredis__redis_OR_pipeline.defineCommand
		|| ioredis__redis_OR_pipeline.call
	) {
		return ioredis__redis_OR_pipeline.zadd(redis_key, score, member)
	}
	const upstash__redis = redis_OR_pipeline as Redis
	// uncommenting these should result in a type error
	// upstash__redis.defineCommand
	// upstash__redis.call
	return upstash__redis.zadd(redis_key, { score, member })
}
```

**Comment by btakita** [comment]
Yeah...I have to say that these incompatibilities are a major roadblock to me using your pay as you go service.

**Comment by chronark** [comment]
We're not planning to add compatibility, you can use ioredis or any other existing redis client with Upstash already.

```ts
import Redis from "ioredis"

const client = new Redis("redis://default:xxxx@xxxx.upstash.io:xxxxx");
await client.set('foo', 'bar');
```
