### ISSUE TITLE
Typescript error for RedisConfigFastly

### ISSUE THREAD

**Issue by davidmturner** [upstash/upstash-redis#353]
Is there a problem with the types for the Fastly client wrapper?

With javascript, there seems to be no issue. However, with typescript the compiler doesn't like the addition of the backend attribute to the config object:

```
import { Redis } from '@upstash/redis/fastly';

const redis = new Redis({
  url: UPSTASH_URL,
  token: UPSTASH_TOKEN,
  backend: UPSTASH_BACKEND
});
```

Seems the platform specific class constructor isn't applying RedisConfigFastly to the config, but no matter how much I stare at the code, I can't tell why not!

Using @upstash/redis version 1.20.6

**Comment by chronark** [comment]
what's the error?

**Comment by davidmturner** [comment]
It's a typescript error. TS2769: No overload matches this call.

```
  Overload 1 of 2, '(config: RedisConfigNodejs): Redis', gave the following error.
    Argument of type '{ url: string; token: string; backend: string; }' is not assignable to parameter of type 'RedisConfigNodejs'.
      Object literal may only specify known properties, and 'backend' does not exist in type 'RedisConfigNodejs'.
  Overload 2 of 2, '(requesters: Requester): Redis', gave the following error.
    Argument of type '{ url: string; token: string; backend: string; }' is not assignable to parameter of type 'Requester'.
      Object literal may only specify known properties, and 'url' does not exist in type 'Requester'.
```

The workaround I'm currently using is to use a type assertion like this:

```
import { Redis } from '@upstash/redis/fastly';
import { RedisConfigFastly } from '@upstash/redis/types/platforms/fastly';

const redis = new Redis({
    url: UPSTASH_URL,
    token: UPSTASH_TOKEN,
    backend: UPSTASH_BACKEND
  } as RedisConfigFastly);
```

**Comment by chronark** [comment]
ooh, I didn't catch it in our CI cause my fastly example was only using js
my bad

I can reproduce it and try to debug further, thanks

**Comment by chronark** [comment]
@davidmturner should be fixed in `v1.21.0`
![CleanShot 2023-05-31 at 13 39 19](https://github.com/upstash/upstash-redis/assets/18246773/93537acf-258b-40d8-9e87-bfe96ba8fc07)

**Comment by davidmturner** [comment]
Yep, works for me. Thanks!

**Comment by kikky7** [comment]
I am getting same error with version 1.21.0
![image](https://github.com/upstash/upstash-redis/assets/57031667/29f34951-8f86-4f81-99d4-bde0ca9e4fa3)
![image](https://github.com/upstash/upstash-redis/assets/57031667/ea1f20dd-0ebf-43fa-8ffd-2b7ad0e1d71a)

**Comment by chronark** [comment]
please import from "@upstash/redis/fastly"
@kikky7
