### ISSUE TITLE
Big number gets wrong while deserialization process

### ISSUE THREAD

**Issue by So-chiru** [upstash/upstash-redis#37]
As title says, big numbers saved in Upstash like `101660004000155481467` are converted to wrong values like `101660004000155480000`.

Here is the saved value on Upstash : 

<img width="463" alt="Screen Shot 2022-03-12 at 2 01 32 PM" src="https://user-images.githubusercontent.com/32066651/158004545-76ba5d22-f98a-488c-9c02-3d3bdc189a33.png">

and this is what I got from the client : 

<img width="627" alt="Screen Shot 2022-03-12 at 2 05 17 PM" src="https://user-images.githubusercontent.com/32066651/158004618-9782aaac-5075-4287-8285-e2db42c4d4bd.png">

It looks like you need to make the deserialize function handle big numbers to prevent these cases.

**Comment by chronark** [comment]
Hey @So-chiru, thank you for reporting this.
The issue comes from javascript not being able to handle numbers larger than `2^53 -1` safely.
I'll release `v1.0.0-alpha.5` in a few minutes with a fix.

In case of very large numbers we now return it in its raw string format.
