### ISSUE TITLE
Use "no-store" fetch breaking Next static rendering

### ISSUE THREAD

**Issue by eric-burel** [upstash/upstash-redis#397]
Hi,

As described in the title, this package seems to explicitely set "no-store" fetch, which is incompatible with build-time only data fetching in Next.js.

I couldn't find an option to pass more parameters to the underlying "fetch" call or setting a different default value, is that doable ?

It's kinda the reverse of this previous issue: https://github.com/upstash/upstash-redis/issues/330

**Comment by chronark** [comment]
yeah we should find a way to make it configurable, while keeping the "no-store" default I think.

**Comment by eric-burel** [comment]
Why not use "default" as the default?

Next.js data fetching with `fetch` is tailored for direct calls. In my understanding, third-party libraries should not try to tweak the caching system to accommodate Next, instead the end user is expected to use React 18 `cache`.
If I rephrase, the fact that you use `fetch` because Upstash connexion is done via HTTP is a purely internal concern of the client, for the end user, it should behave as any other database client (that usually rely on a persisting TCP connection) => you want end users to rely on React `cache` not on `fetch`configuration.

**Comment by eric-burel** [comment]
Also perhaps using `dynamic = force-static` at page level could work: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
I'll give it a shot

**Comment by eric-burel** [comment]
Re: `force-static` doesn't seem to work reliably in production, I still get `DynamicServerError: Dynamic server usage: no-store fetch` with a 500

**Comment by francofantini** [comment]
Hi there! This is a dealbreaker for using Upstash Redis with Next app dir. 

Is there any known workarounds?

**Comment by francofantini** [comment]
I've just opened #405. let me know what you think @chronark

**Comment by vvo** [comment]
Hey @eric-burel, late to the party but can you precise why you said:

> As described in the title, this package seems to explicitely set "no-store" fetch, which is incompatible with build-time only data fetching in Next.js. 

? Thanks!

**Comment by eric-burel** [comment]
@vvo when using Upstash I end up with `DynamicServerError: Dynamic server usage: no-store fetch`, which after digging seems related to the fact that Next.js patches all "fetch" calls, including fetch calls in 3rd party libs. 
So if the 3rd party lib uses "no-store", you cannot statically render any page that uses this lib. It's treated the same as if you used this value in your own code to indicate a dynamic data fetch, but you have no control over it so you're stuck.

It seems that "force-static" didn't help, so there might be an issue in Next.js too.

This should be fixed by #405 but not sure if it has been released.

**Comment by chronark** [comment]
https://github.com/upstash/upstash-redis/releases/tag/v1.22.0

should be in this one
