### ISSUE TITLE
Missing CLIENT (LIST/SETNAME) command?

### ISSUE THREAD

**Issue by manast** [upstash/upstash-redis#422]
I could not find in the compatibility list if the command CLIENT LIST and CLIENT SETNAME commands are supported. Seems like CLIENT LIST just returns an empty list. Are there any plans to support these commands?

https://redis.io/commands/client-list/

**Comment by mdogan** [comment]
CLIENT SETNAME and CLIENT GETNAME are supported and as you figured out CLIENT LIST returns empty array at the moment. We will implement CLIENT LIST soon.

**Comment by manast** [comment]
Bump.

**Comment by chronark** [comment]
@ogzhanolguncu

**Comment by ogzhanolguncu** [comment]
Right now, the REST API doesn't have the "Client list" feature, but as soon as they add it in there, I'll make sure to include it in the SDK. I'll also chat with the team to see if we can speed things up a bit.

**Comment by manast** [comment]
Bump!

**Comment by ogzhanolguncu** [comment]
https://upstash.com/docs/redis/overall/rediscompatibility you can also follow here. Once its here i'll implement it in no time.
