### ISSUE TITLE
TypeError: Redis.fromEnv is not a function

### ISSUE THREAD

**Issue by flieks** [upstash/upstash-redis#44]
With the 1.0.0 release i get
TypeError: Redis.fromEnv is not a function

I am not using typescript.

Code is:

```
import { Redis, auth, get } from '@upstash/redis';
const client = Redis.fromEnv()
```

**Comment by chronark** [comment]
Just tried it and it works as expected.
Does it say `fromEnv` is not a function or one of the other imports (`auth` or `get`)? Because importing commands directly is no longer possible. You can access them after creating the `Redis` instance:

```ts
import { Redis } from "@upstash/redis"
const redis = Redis.fromEnv()
const res = await redis.get("myKey")
```

**Comment by flieks** [comment]
hmm it is working now which is great
i forgot to remove the old 
`const Redis = require("ioredis");` and also removed the auth, and get/set from the imports as you suggested.
Thanks!
