### ISSUE TITLE
Return type for Redis#exists is wrong

### ISSUE THREAD

**Issue by alii** [upstash/upstash-redis#47]
Right now, the return type is marked as `0 | 1` when it should in fact simply be `number`:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/25351731/159384144-d4925413-d21c-4289-a868-856942c0ac99.png">

Relevant Redis docs: https://redis.io/commands/exists
<img width="603" alt="image" src="https://user-images.githubusercontent.com/25351731/159384159-461bbecb-21ac-4b28-b58e-59ec3dfc45d0.png">

**Comment by chronark** [comment]
Correct, my bad. I'll roll out a fix tonight.
Thanks for reporting it.
