### ISSUE TITLE
Feature request: Do not automatically deserialize object

### ISSUE THREAD

**Issue by thomasdao** [upstash/upstash-redis#49]
Hi,

Currently when `get` a string from Redis, the result is automatically deserialized with `JSON.parse`. I find this feature a bit unexpected, since I know the string format, and in my project it's not JSON, so I don't need the automatic conversion.

Would it be possible to disable the automatic deserialization? I find defining `CustomGetCommand` with custom deserialize function is a bit troublesome to use. The most straightforward way is just return String and the client can deserialize the result themself.

**Comment by chronark** [comment]
Hi @thomasdao, thanks for the request.
I totally see your point and implement it asap.

Can you give me an example of what you are storing?
The current implementation should not deserialize it if it's not valid json. So maybe there's a bug somewhere.

**Comment by thomasdao** [comment]
Hi @chronark, thanks for a really fast reply :) This FR is probably more about the API and not really about bug :).

When I just get started with Upstash, I wanted to store an object to Redis, so I use `JSON.stringify` to convert the object to String. When I get back the string, I use `JSON.parse` to convert the result to object and find it surprising that this failed. I kind of expect that if I store a string, I should get back a string instead of an object.

**Comment by chronark** [comment]
@thomasdao 
I released `v1.3.3-alpha.0`
You can get it with `npm install @upstash/redis@next`
```ts
const redis = new Redis({
    // ...
    automaticDeserialization: false,
}) 

// or
const redis = Redis.fromEnv({
    automaticDeserialization: false,
}) 
```
This probably breaks quite a few types, but it's a first step in that direction. Will take some time to test/document everything before we'll release this


Please report any issues here, thank you.

**Comment by chronark** [comment]
Closing this as there have not been any reported issues.
Please open a new issue if you encounter a bug.

**Comment by fevernova90** [comment]
There's a broken type while using `automaticDeserialization: false`.

@upstash/redis: 1.21.0

```typescript
import { Redis } from "@upstash/redis";
const redis = Redis.fromEnv({
  automaticDeserialization: false,
});
const pattern = 'your_pattern';
const scanRes = await redis.scan(0, { match: pattern, count: 100 });
const cursor = scanRes[0]; // The cursor here is returning string at runtime, while the type is number.
```

**Comment by eakl** [comment]
There's also an inconsistency for number represented as string.

```ts
await kv.hset(`key`, {
   code1: '123456',
   code2: '000001'
})

const value = await kv.hgetall(`key`)

console.log(typeof data.code1) // number
console.log(typeof data.code2) // string
```

```ts
console.log(typeof 12345) // number
console.log(typeof JSON.stringify(12345)) // string
console.log(typeof JSON.parse(JSON.stringify(12345))) // number

console.log(typeof '12345') // string
console.log(typeof JSON.stringify('12345')) // string
console.log(typeof JSON.parse(JSON.stringify('12345'))) // string
```

`Date` is also serialized but not deserialized

**Comment by ScreamZ** [comment]
@chronark @ogzhanolguncu 

For safe serialization can we expect you to include https://github.com/flightcontrolhq/superjson as default serializer ?

Or add capability to switch the default serializer and parser, and not just disable. This would fix date and many other things and allow to add custom serializer.

This lib is also recommended in production by tRPC

**Comment by CahidArda** [comment]
Hi @ScreamZ,

We can easily make it possible to add your own deserializer like this:

```ts
const redis = new Redis({ ..., deserializer: "your-deserializer" })
```

as for serialization, can you share a use case so we can understand it better?

**Comment by ScreamZ** [comment]
Thanks for answering

https://github.com/nextauthjs/next-auth/blob/8c0081553889b379831a2dd5db79798621a0903b/packages/adapter-upstash-redis/src/index.ts#L196-L219

As you can see here, we serialize a VerificationToken which contains a Date  `expires` but when unserialized, the date is a string. Therefore we have to hydrate date using a function.

Using superJSON, we could skip this step always.

SUperJSON also allows to use custom serializer. To serialize whatever you want, like buffers.

**Comment by ytkimirti** [comment]
Hi @ScreamZ, that sounds pretty useful to me. I opened a separate ticket for tracking, #1332
