### ISSUE TITLE
JSON parse loses precision for large numbers

### ISSUE THREAD

**Issue by timlrx** [upstash/upstash-redis#497]
## Bug Report

Saving a large integer to redis and retrieving it via the CLI works but retrieving it with `hgetall` returns a different result.

The issue is probably due to [`JSON.parse`](https://github.com/upstash/upstash-redis/blob/9b75ea104a3ebdcee8ce0360302782200938999c/pkg/commands/hgetall.ts#L14) losing precision.

**Comment by chronark** [comment]
it's more likely due to javascript not being able to handle large numbers
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

can you share an example where it failed?
would love to reproduce this

**Comment by timlrx** [comment]
> it's more likely due to javascript not being able to handle large numbers https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
> 
> can you share an example where it failed? would love to reproduce this

Here's an example:
```
HSET testKey name abc userId 10769150350006150715113082367
```

And here's the js code:
```
const results = await kv.hgetall(`testKey`)
console.log(results['userId'])
const id = await kv.hget<string>(`testKey`, 'userId')
console.log(id)
```

`id` returns the correct value and is different from `results['userId']`

**Comment by timlrx** [comment]
For context, I was trying to store a [google oauth payload](https://developers.google.com/identity/openid-connect/openid-connect#an-id-tokens-payload)

**Comment by timlrx** [comment]
The fix won't work as redis will still store it as a number anyway. Tried it with the library and via CLI as well. Will just make an extra call for the time being, to retrieve the right value.

**Comment by ogzhanolguncu** [comment]
@timlrx, I believe the issue arises when you pass large numbers in JavaScript, like `10769150350006150715113082367`. Since this number is greater than `1e21`, JavaScript automatically converts it to scientific notation, represented as `1.076915035000615e+28.` This conversion can result in a loss of precision. This is why you don't encounter the same problem when using the CLI and REST API, as they don't perform this automatic conversion.

**Comment by timlrx** [comment]
`HGET` does the trick since it returns the id as a string rather than a js number. I think that's probably the best workaround for fields that might exceed `Number.MAX_SAFE_INTEGER`. Closing this issue since it is not a problem with the library.

**Comment by ogzhanolguncu** [comment]
Yeah, it seems like its the only option now.
