### ISSUE TITLE
Pipeline feature?

### ISSUE THREAD

**Issue by arclogos132** [upstash/upstash-redis#5]
Does this have a redis pipeline feature?

**Comment by ademilter** [comment]
@arclogos132 not yet but we will support it as soon as possible 🤞

**Comment by kay-is** [comment]
@mdogan @ademilter any timeline?

I'm just asking because the next-auth people asked about it.

**Comment by mdogan** [comment]
@kay-is; pipeline support is planned for the current project cycle, so most probably around end of January.

**Comment by enesakar** [comment]
preferred API:
const { data } = await pipeline()
  .set(key, 'hello')
  .get(key)
  .submit();

**Comment by chronark** [comment]
@kay-is I'll have a pr ready within the coming week and after reviews we can release it soon.
