### ISSUE TITLE
Support additional environments

### ISSUE THREAD

**Issue by obibring** [upstash/upstash-redis#50]
Hi there,

### Issue
I'm using this library in the context of a browser plugin where http requests can't be issued reliably unless proxied through a background script using apis not compatible w/ `window.fetch`.

### Workaround

I'm able to support this by overriding the `HttpClient` and `Redis` classes like so:

```typescript
class CustomHttpClient extends HttpClient {
  constructor(config: HttpClientConfig, private fetch: FetchFunctionLike) {
     super(config)
  }
  request<TResponse>(req: HttpRequest): Promise<TResponse> {
     const url = [this.baseUrl, ...(req.path || [])].join("/");
     return this.fetch(url, { method: "POST", headers: this.headers, body: JSON.stringify(req.body) });
  }
}
```

```typescript
class CustomRedis extends Redis {
  constructor(config: RedisConfigNodejs, client: HttpClient) {
     super(config);
     this.client = client;
  }
}
```

### Ask
Would it be possible to either:
1. Alter the `Redis` constructor to accept either a config object or an `HttpClient` instance to its constructor?
2. Expose `client` as a non-private instance variable on the `Redis` class to allow custom child classes to set its value?

This might have the added benefit of providing the same benefits of importing individual commands and issuing them individually but with a simpler api.

Thanks!

**Comment by chronark** [comment]
Hey @obibring!

The underlying implementation already acccepts an implementation of `HttpClient`. We're just not exporting that and instead export a thin wrapper but that can be changed easily.

I'll do it next week.

**Comment by obibring** [comment]
Thanks!

**Comment by chronark** [comment]
@obibring You can now do:
```ts
import { UpstashRequest, Requester, UpstashResponse, Redis } from "@upstash/redis"

const requester: Requester = {
  request: <TResult>(req: UpstashRequest): Promise<UpstashResponse<TResult>> => {
     // ...
   }
 }
  const redis = new Redis(requester)
 ```

**Comment by obibring** [comment]
@chronark many thanks 🙏
