### ISSUE TITLE
[feature request] Export map with runtime keys

### ISSUE THREAD

**Issue by Hebilicious** [upstash/upstash-redis#515]
It would be great if you would provide an export map which follow each platform runtimeKey specifier.
 https://runtime-keys.proposal.wintercg.org/
 
Ideally we should be able to use `import { Redis } from "@upstash/redis"` on every provider, and runtime/bundlers should follow the export map to load the correct file.

This can be adopted additionally to the current export map, that way it won't break anyone code.

**Comment by chronark** [comment]
Oh I love this, thanks for letting us know.
That's way better :)

**Comment by ogzhanolguncu** [comment]
@Hebilicious Hey, is it possible for you to share a repo that utilizes runtime keys as you described? I'll be happy to help you out.

**Comment by Hebilicious** [comment]
@ogzhanolguncu Sorry I missed this. Here's an example https://github.com/unjs/uncrypto/blob/main/package.json

**Comment by Hebilicious** [comment]
I can open a PR for this if you want @chronark @ogzhanolguncu

**Comment by ogzhanolguncu** [comment]
@Hebilicious PRs are welcome.
