### ISSUE TITLE
"CONFIG GET databases" returns the empty string instead of the number of databases

### ISSUE THREAD

**Issue by bubnov** [upstash/upstash-redis#526]
Hello,

I use upstash redis in fly.io. But for some reason when I call the `CONFIG GET databases` command I didn't get the number of databases:

```
127.0.0.1:16379> CONFIG GET databases
1) "databases"
2) ""
```

If I call the same command for the local redis instance, I will get proper response:

<img width="238" alt="image" src="https://github.com/upstash/upstash-redis/assets/818612/3e2aad92-df3d-4dea-bc96-fd4cbab17be0">

```
[
  {
    "field": "databases",
    "value": "16"
  }
]
```

Could you please explain this difference?

Is it somehow related to this configuration in https://raw.githubusercontent.com/redis/redis/unstable/redis.conf?

```
# Set the number of databases. The default database is DB 0, you can select
# a different one on a per-connection basis using SELECT <dbid> where
# dbid is a number between 0 and 'databases'-1
databases 16
```

Thanks!

**Comment by chronark** [comment]
we're not running stock redis but a custom implementation with Redis-compatible api
we only support db1, so this command likely is implemented as a noop

**Comment by bubnov** [comment]
@chronark, I think the issue can be closed, as the main problem I had was related to the products of JetBrains, which had a bug with handling this specific case. They said that the issue is already fixed.

Thanks!
