### ISSUE TITLE
How to implement redlock with Upstash redis library?

### ISSUE THREAD

**Issue by Jonatthu** [upstash/upstash-redis#592]
Is there any way to integrate Redlock?
https://github.com/mike-marcacci/node-redlock

The repo says that is deeply integrated with 
https://github.com/redis/ioredis

I wonder if that's a problem and how to solve it.

**Comment by chronark** [comment]
you can use ioredis with upstash just fine :)

**Comment by Jonatthu** [comment]
I was wondering on the case of Serveless and/or on the edge case scenarios like AWS Lambda or Vercerl functions @chronark

**Comment by chronark** [comment]
Ah gotcha,

I haven't checked what commands redlock is using, probably a lot of `eval`. But it would be possible and not too hard to build a small adapter, that takes in an @upstash/redis instance and can then be used by redlock?

**Comment by Jonatthu** [comment]
I would love to have it as part of official support like @upstash/redlock

**Comment by ogzhanolguncu** [comment]
We're putting together our own take on a distributed lock using Redis. Not sure if it'll end up being called "redlock," but that's definitely the direction we're headed in.

**Comment by ShravanSunder** [comment]
@ogzhanolguncu so  is this done? Can you link to  the solution?

**Comment by ogzhanolguncu** [comment]
Once it's done i'll ping it here.

**Comment by MeshanKhosla** [comment]
@ShravanSunder Sorry I didn't send this earlier, but the lock SDK was releasesd a few weeks ago: https://github.com/upstash/lock/tree/main
