### ISSUE TITLE
deserialisation issues on hgetall

### ISSUE THREAD

**Issue by borjadotai** [upstash/upstash-redis#699]
Hi there, I have started using vercel's kv today and stumbled upon a very bizarre issue. 

I was using `hmset` as they do in their ai template to store chats on my kv/upstash/redis and then using `hgetall` to get them. However, in their examples, the payload store contains a github user id, which is a relatively small number and so all is well. 
Very unexpectedly, things change when you swap auth provider to Google.

Googles sub / ids are larger numbers and when adding that number in the payload - bare in mind I am setting it as a string on that payload, not a number - everything breaks, why?

An example of a google sub id is something like this: `106242075399214372653`
KV/Upstash/Redis was returning that exact value when querying it on the CLI.
However, when running `kv.hgetall` which is a wrapper around upstash's, it returned `106242075399214370000`.

How strange I thought, it seems to be rounding it as if it didn't have enough memory for the number, but it is a string. It is stored in redis as a string and when I query it through CLI it gives the right value, why would it round it as a number then...?

I then though, let me try a different method and picked it straight up with `kv.hget(`chat:${id}`, 'userId')`. Guess what, through this method picking the value directly, it returned `106242075399214372653` as expected.

So surely there must be some serialisation going on on the `kv.hgetall` method that is causing this...
I got into [@vercel/kv](https://github.com/vercel/storage/blob/main/packages/kv/src/index.ts) to see it's a wrapper of Upstash Redis so I come here...

I dig a little bit to find this [HGetAllCommand](https://github.com/upstash/upstash-redis/blob/d520cbfb3d6ecd9e996eec414053191d8ddacaeb/pkg/commands/hgetall.ts#L3) and surprise, surprise, there is indeed a `deserialize` function in there. 

Now, reading the function, if I understand the code correctly, it seems like my google sub should actually be considered a `valueIsNumberAndNotSafeInteger`.
`!Number.isNaN(Number('106242075399214372653')) && !Number.isSafeInteger('106242075399214372653') === true`) 

So it should be passed as is, however, clearly it is going down the other logical path and being `JSON.parse()` which is what is causing the round issue.
`JSON.parse('106242075399214372653') === 106242075399214370000` 
This is what the `kv.hgetall` function was returning for my userId value.

I was going to make a PR to fix the `deserialize` since the issue is that clearly for my google sub number, the check must be failing and going into the JSON.parse but the logic seems right so I thought I'd open this up to see if someone smarter picks up what I might be missing, thanks! 😄

**Comment by ogzhanolguncu** [comment]
I think we can use the `reviver` parameter in `JSON.parse` to convert `bigint` values into `strings`. I'll begin testing this and update you shortly.

**Comment by ogzhanolguncu** [comment]
I just checked [@vercel/kv](https://github.com/vercel/storage/blob/main/pnpm-lock.yaml) and found that they're using the @upstash-redis version 1.22.0. This version uses a **default deserialize** that applies JSON.parse to everything without checking the actual data type. That's likely the reason for your parsing problem. Maybe you should bring this up with [@vercel/kv](https://github.com/vercel/storage/blob/main/packages/kv/src/index.ts) on their issue tracker?

**Comment by borjadotai** [comment]
Amazing, thanks for looking into this, I'll bring it up to them too 😄
