### ISSUE TITLE
Unable to find Type SetCommandOptions after updating package to 1.24.1 from 1.22.0

### ISSUE THREAD

**Issue by cosileone** [upstash/upstash-redis#700]
After updating this package from 1.22.0 to 1.24.1 I am no longer able to import the typescript Type for SetCommandOptions

`import { type SetCommandOptions } from "@upstash/redis/types/pkg/commands/set";`

Instead getting an error that the specified module cannot be found. Is there a preferred way get those types?

**Comment by chronark** [comment]
Hey, we didn't know people used the types as they were not explicitely exported.

We'll sort that out and make them available again!

**Comment by cosileone** [comment]
Thanks for the quick reply!

> We'll sort that out and make them available again!

This will be greatly appreciated. I have a lightweight wrapper around the `redis.set` command and am choosing to transparently send the caching options.

Something along the lines of this:
```typescript
export async function setCachedData(
  key: string,
  data: unknown,
  options?: SetCommandOptions
): Promise<void> {
  const dataString = JSON.stringify(data, bigIntSerializer);
  await redis.set(key, dataString, options);
}
```

Love the responsiveness! Keep up the good work

**Comment by ogzhanolguncu** [comment]
Hey, @cosileone, now you will be able to access types like this

```
import { Redis,SetCommandOptions, SetCommand } from "@upstash/redis";
```

**Comment by cosileone** [comment]
Thanks everyone! Love the quick turnaround
