### ISSUE TITLE
UpstashError: Unauthorized

### ISSUE THREAD

**Issue by stolinski** [upstash/upstash-redis#711]
Using the latest, I've copied the code directly from Connect to your database, section

```
import { Redis } from '@upstash/redis'

const redis = new Redis({
  url: 'https://*****.upstash.io',
  token: '********',

})

const data = await redis.set('foo', 'bar');
```
My token was copied directly from

<img width="151" alt="Screenshot 2023-11-02 at 4 18 52 PM" src="https://github.com/upstash/upstash-redis/assets/669383/f2ea4daf-7798-4a2b-99a0-f41c69a74aed">

and verified to be loaded. 

However this immediately fails with Unauthorized and no other information.

I noticed the node redis and ioredis versions use the port in the url where the @upstash/redis doe not. Is that the issue? If not more detail in the error message or anything to point as to why a valid token with your quick start code would fail.

**Comment by stolinski** [comment]
Ok so apparently password is not what the API is wanting in token. I think the UI in the dashboard makes this very confusing because the REST API sections and Connect to your database are completely separate. In addition the langue UPSTASH_REDIS_REST_TOKEN has no indication that is to be use as token property in the connnect to your db code. I think there are lot of opportunities to make this more clear.

**Comment by amaury901130** [comment]
is here:
<img width="561" alt="Screenshot 2024-04-23 at 18 14 40" src="https://github.com/upstash/upstash-redis/assets/17047904/24fff072-8da0-43b9-af98-0f82ad36cfd9">

**Comment by BenAHammond** [comment]
> is here: <img alt="Screenshot 2024-04-23 at 18 14 40" width="561" src="https://private-user-images.githubusercontent.com/17047904/324997220-24fff072-8da0-43b9-af98-0f82ad36cfd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzUzMzQsIm5iZiI6MTcxNDY3NTAzNCwicGF0aCI6Ii8xNzA0NzkwNC8zMjQ5OTcyMjAtMjRmZmYwNzItOGRhMC00M2I5LWFmOTgtMGY4MmFkMzZjZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE4MzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1M2VmNGNiYzdkYTJiZDJiMTFkM2ZjNjlhMWFkYzkwOWZmNDZmMTUyNDE3NDRhOGQxZTQ4NzkxODQ5NWJjMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KeYrwt5it2sYEiQhBtBzRh04LaXlloko4GwbIQ-jbgo">

Wow, why is this critical button _so_ **_tiny_**?
