### ISSUE TITLE
Nuxt Build Error: `RollupError: Could not resolve "./chunk-SMBYCQIJ.js" from "./chunk-SMBYCQIJ.js?commonjs-external"`

### ISSUE THREAD

**Issue by McPizza0** [upstash/upstash-redis#774]
When using a recent `@upstash/redis` with Nuxt
I get build errors and can not initialize the client
`RollupError: Could not resolve "./chunk-SMBYCQIJ.js" from "./chunk-SMBYCQIJ.js?commonjs-external"`

Reverting to version 1.20.0 solves this issue

Seems it could be related to the switch from deno  to bun+tsup

**Comment by ogzhanolguncu** [comment]
If its possible can you share a repo or a way to reproduce this?

**Comment by ytkimirti** [comment]
I still did not understand why nuxt didn't work with the commonjs version but using esm seems to solve the problem

**Comment by BlayTheNinth** [comment]
Still experiencing this on v1.28.1: https://stackblitz.com/edit/github-ciuwhg-84oljk?file=package.json

**Comment by McPizza0** [comment]
please re-open
confirm that its still erroring @ytkimirti

**Comment by ytkimirti** [comment]
Yes you are correct, i will try fixing this today

**Comment by awaisalwaisy** [comment]
Another candidate: ERROR  RollupError: Could not resolve "./chunk-KFJRJ4VJ.js" from "./chunk-KFJRJ4VJ.js?commonjs-external"

**Comment by ytkimirti** [comment]
@awaisalwaisy @McPizza0 
The export map was not working because it was inverted 🤦. We released a new version `v1.28.2`, I tried locally an it seems to work fine now. Sorry for all the trouble and thanks for helping on the issue 🙏

**Comment by McPizza0** [comment]
thanks @ytkimirti looks to be solved
