### ISSUE TITLE
Missing GT / LT options for ZADD command

### ISSUE THREAD

**Issue by mnemitz** [upstash/upstash-redis#777]
Hello,

I'm using Vercel's KV library (which appears to use this library to interface with Redis), and I've noticed that the `LT` and `GT` command options for the `ZADD` operation are not present in the `ZAddCommandOptions` interface.

```typescript
type ZAddCommandOptions = ({
    nx: true;
    xx?: never;
} | {
    nx?: never;
    xx: true;
} | {
    nx?: never;
    xx?: never;
}) & {
    ch?: true;
};
```

Only the `NX`, `XX` and `CH` options are covered here.

Documentation for the options is here: https://redis.io/commands/zadd/

**Comment by ogzhanolguncu** [comment]
@mnemitz Now you have to let Vercel KV team know that they can bump their version so you can start using `LT`,`GT`
