### ISSUE TITLE
Using Docker Redis with this package?

### ISSUE THREAD

**Issue by elie222** [upstash/upstash-redis#802]
Hey,

We use this package for: https://github.com/elie222/inbox-zero

Curious if there's an easy way for it to work with a Docker Compose Redis? To make it easier for people to get started with our app and not force them to use Upstash for Redis.

**Comment by ogzhanolguncu** [comment]
Check this out https://github.com/hiett/serverless-redis-http.

**Comment by jgresham** [comment]
> Check this out https://github.com/hiett/serverless-redis-http.

This worked for me on Mac... 
Just replace `podman` with `docker` and `host.containers.internal` with docker's value (`host.docker.internal`?)
```
podman run \
    --rm -d -p 8080:80 --name redis-http \
    -e SRH_MODE=env \
    -e SRH_TOKEN=dummy_token \
    -e SRH_CONNECTION_STRING="redis://host.containers.internal:6379" \
    hiett/serverless-redis-http:latest
```

And redis server running with `brew install redis && redis-server`
