### ISSUE TITLE
Pipelines don't return values for TTL

### ISSUE THREAD

**Issue by devjmetivier** [upstash/upstash-redis#820]
Example:

```ts
// imported redis client with proper credentials...

const keys = await redis.keys('*');

const ttlsPipeline = redis.pipeline();
keys.forEach((key) => ttlsPipeline.ttl(key));

const ttls = await ttlsPipeline.exec<number[]>();

console.log(ttls) // <- always `null` 🤔❓
```

I hesitated making this issue because I look at this at face value and think I must be doing something wrong, but it seems like such a trivial query that it ought to work as written.

Any help would be greatly appreciated!

> Note: The Upstash DB I'm using for this is for testing, so the quantity of keys is low.

**Comment by ytkimirti** [comment]
Hey @devjmetivier, did you fix the problem?

**Comment by ytkimirti** [comment]
Thanks for sharing this with us. I was not able to reproduce this issue. If the issue is still persisting you can send an email to support@upstash.com with your database name. We would be happy to investigate the reason behind it.
