### ISSUE TITLE
Client takes too long to complete command

### ISSUE THREAD

**Issue by schulzf** [upstash/upstash-redis#848]
I've been experiencing averages of 1600ms on executing a simple set command with `upstash-redis` (sometimes it takes ~4000ms as you can see on the image below), after switching to `ioredis` have averages of 200ms.

![image](https://github.com/upstash/upstash-redis/assets/56260943/4ca19c2e-667b-48d4-bdab-4f76c7d48a3f)

**Comment by ytkimirti** [comment]
Thank you for notifying us. Could you send an email to us at [support@upstash.com](mailto:support@upstash.com) with your database endpoint so we can investigate this further?
