### ISSUE TITLE
Exists command to Edge always returning 0?

### ISSUE THREAD

**Issue by arclogos132** [upstash/upstash-redis#9]
Exists command to Edge always returning 0?

**Comment by arclogos132** [comment]
Fixed

**Comment by arclogos132** [comment]
This issue was tagged on the latest release but exists command still returns only zero.

**Comment by Kikobeats** [comment]
I'm experimenting with the same issue. 

Some debugging information:

- v0.1.11: works fine
- v0.1.21: broken (it always returns 0)
- v0.1.22: broken (it always returns 0)

**Comment by ademilter** [comment]
we are working on it
