### ISSUE TITLE
Add an opt-in to per-command latency logging

### ISSUE THREAD

**Issue by cramforce** [upstash/upstash-redis#907]
It'd be great to be able to emit log lines lines with per-command latency info. It's very hard to manually add this logging in an application.

**Comment by ogzhanolguncu** [comment]
Hey, can you elaborate a bit?

**Comment by cramforce** [comment]
The more general problem is that if you have a sophisticated applications, and your tracing system tells you that some requests to Upstash are slow, then it is very hard to figure out which Redis commands were even being run.

**Comment by ogzhanolguncu** [comment]
Got it. I’ll see what I can do and let you know.

**Comment by ogzhanolguncu** [comment]
@cramforce https://github.com/upstash/upstash-redis/pull/958 I believe this is it.

**Comment by ogzhanolguncu** [comment]
@cramforce latency logging released in [v1.29.0](https://github.com/upstash/upstash-redis/releases/tag/v1.29.0)
