### ISSUE TITLE
Upstash Redis fails to connect to Redis Rust using a MultiplexedConnection

### ISSUE THREAD

**Issue by spiceee** [upstash/upstash-redis#974]
### Description

Upstash Redis fails to connect to [redis-rs](https://docs.rs/redis/latest/redis/), the most used Redis Rust crate when using a `MultiplexedConnection` which is the type of connection that is safe to share between multiple threads in Rust.

I've created a repo to demo the problem: https://github.com/spiceee/upstash-redis-bug

Besides making sure `MultiplexedConnection` works with vanilla Redis, I've also tested other Redis vendors, and they work fine with redis-rs.

It is probably worth mentioning that we are creating Upstash Redis instances through our vendor, Vercel.

**Comment by mdogan** [comment]
Can you post the error message and error stacktrace please? Is your database TLS enabled? If yes, did you enable TLS config in Redis client?

**Comment by spiceee** [comment]
@ogzhanolguncu @mdogan I've enabled TLS in `redis-rs` and it fixed the issue. I had forgotten that Vercel only creates TLS-enabled databases via their dashboard. I will close this issue!

**Comment by ogzhanolguncu** [comment]
@spiceee Glad to hear that. Let us know if you need any help.
